/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nfaFactorySol from "./NFAFactory.sol";
export type { nfaFactorySol };
export type { Lock } from "./Lock";
